# Generated by Django 4.2.2 on 2023-06-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_emailrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='action_done',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='ticket_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailrequest',
            name='username',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
