# Generated by Django 4.2.2 on 2023-06-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_emailrequest_action_done_emailrequest_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
