# Generated by Django 4.2.2 on 2023-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_emailrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='actions',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
