# Generated by Django 4.2.2 on 2023-06-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_categories_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrequest',
            name='email_id',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
