# Generated by Django 4.2.2 on 2023-06-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_emailrequest_email_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='categories',
            name='actions',
        ),
        migrations.AddField(
            model_name='categories',
            name='actions',
            field=models.ManyToManyField(to='crm.actions'),
        ),
    ]
