# Generated by Django 4.2.2 on 2023-06-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_actions_remove_categories_actions_categories_actions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='lable',
            new_name='label',
        ),
    ]
