# Generated by Django 4.2.2 on 2023-06-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_emailtemplate_alter_categories_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_to',
            field=models.CharField(default=None, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
