# Generated by Django 4.2.2 on 2023-06-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_emailtemplate_email_to_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
