# Generated by Django 4.2.2 on 2023-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_emailtemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
