# Generated by Django 4.2.2 on 2023-06-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_actions_is_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='body',
            new_name='html',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='design',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
