# Generated by Django 4.2.2 on 2023-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_rename_body_emailtemplate_html_emailtemplate_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
