# Generated by Django 4.2.2 on 2023-07-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_smtpemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='actions',
        ),
    ]
