# Generated by Django 4.2.2 on 2023-07-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_categories_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.categories'),
        ),
    ]
