# Generated by Django 4.2.2 on 2023-07-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_actions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_category', to='crm.categories'),
        ),
    ]
