# Generated by Django 4.2.2 on 2023-07-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_actions_template_alter_actions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.actions'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_category', to='crm.categories'),
        ),
    ]
