# Generated by Django 4.2.2 on 2023-09-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0018_emailtemplate_action_alter_actions_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="actions",
            name="email_template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.emailtemplate",
            ),
        ),
    ]
