# Generated by Django 4.2.2 on 2023-09-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0019_actions_email_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actions",
            name="email_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.emailtemplate",
            ),
        ),
    ]
