import { formatDate } from "../utils/helpers";

export const ACCESS_TOKEN_KEY = "ACCESS_TOKEN";
export const REFRESH_TOKEN_KEY = "REFRESH_TOKEN";
export const DEFAULT_LANGUAGE = "DEFAULT_LANGUAGE";
export const USER_DETAILS = "user_details";
export const ACTIVE_FORM = {
  id: Math.random() + Date.now(),
  isPined: false,
  name: "",
  description: "",
  blocks: [],
  fields: [],
  conditions: [],
  createdAt: formatDate("2024-07-07T13:21:06.408+00:00"),
  lastEditedAt: formatDate("2024-07-07T13:21:06.408+00:00"),
};
export const FORM_FIELD_CONDITIONS = {
  date: [
    { id: 1, name: "Equals", slug: "equals" },
    { id: 2, name: "Not Equals", slug: "not_equals" },
    { id: 3, name: "Is Before", slug: "is_before" },
    { id: 4, name: "Is After", slug: "is_after" },
    { id: 5, name: "Today", slug: "today" },
    { id: 6, name: "Current Week", slug: "current_week" },
    { id: 7, name: "Current Month", slug: "current_month" },
    { id: 8, name: "Last 3 Months", slug: "last_three_months" },
    { id: 9, name: "Last 1 Month", slug: "last_one_month" },
    { id: 10, name: "Tomorrow", slug: "tomorrow" },
    { id: 11, name: "Next Month", slug: "next_month" },
  ],
  other: [
    { id: 1, name: "Equals", slug: "equals" },
    { id: 2, name: "Not Equals", slug: "not_equals" },
    { id: 3, name: "Starts With", slug: "starts_with" },
    { id: 4, name: "Doesn't Starts With", slug: "not_starts_with" },
    { id: 5, name: "Ends With", slug: "ends_with" },
    { id: 6, name: "Doesn't Ends With", slug: "not_ends_with" },
    { id: 7, name: "Contains", slug: "contains" },
    { id: 8, name: "Doesn't Contains", slug: "not_contains" },
    { id: 9, name: "Is empty", slug: "is_empty", disable: true },
    { id: 10, name: "Is not empty", slug: "is_not_empty" , disable: true },
  ],
};

export const CLIENTS = {
  data: {
    success: true,
    field: [
      {
        last_form_date: "Last form date",
      },
      {
        marksheet: "Marksheet",
      },
      {
        age: "Age",
      },
      {
        hok_donor: "Hok donor",
      },
      {
        first_name_4: "First name",
      },
      {
        "style_-_source": "Style - source",
      },
      {
        car: "Car",
      },
      {
        language_at_home: "Language at home",
      },
      {
        "husband's_occupation": "Husband's occupation",
      },
      {
        "woman's_occupation": "Woman's occupation",
      },
      {
        "first_name_-_owner": "First name - owner",
      },
      {
        "first_name_-_woman": "First name - woman",
      },
      {
        "b.r.": "B.r.",
      },
      {
        home_phone_1: "Home phone",
      },
      {
        woman_phone: "Woman phone",
      },
      {
        email: "Email",
      },
      {
        home_phone: "Home phone",
      },
      {
        city: "City",
      },
      {
        street: "Street",
      },
      {
        house_number: "House number",
      },
      {
        personnel_id_plus: "Personnel id plus",
      },
      {
        "שווער_-_חתן": "שווער - חתן",
      },
      {
        parent_id_number: "Parent id number",
      },
      {
        mom_id_number: "Mom id number",
      },
      {
        zip_code: "Zip code",
      },
      {
        children_at_home: "Children at home",
      },
      {
        married_children: "Married children",
      },
      {
        full_name: "Full name",
      },
      {
        email_1: "Email",
      },
      {
        first_name: "First name",
      },
      {
        last_name_1: "Last name",
      },
    ],
    data: [
      {
        last_form_date: "2023-03-16T08:23:32Z",
        marksheet: "",
        age: "",
        hok_donor: "",
        first_name_4: "",
        "style_-_source": "",
        car: true,
        language_at_home: "",
        "husband's_occupation": "",
        "woman's_occupation": "",
        "first_name_-_owner": "יצחק יעקב",
        "first_name_-_woman": "",
        "b.r.": "",
        home_phone_1: "+972583230207",
        woman_phone: "+972583230205",
        email: "012yyh@gmail.com",
        home_phone: "+97225630349",
        city: "ירושלים",
        street: "אלקנה",
        house_number: "14",
        personnel_id_plus: "",
        "שווער_-_חתן": "",
        parent_id_number: "",
        mom_id_number: "",
        zip_code: "",
        children_at_home: "",
        married_children: "",
        full_name: "",
        email_1: "",
        first_name: "",
        last_name_1: "",
        id: 2,
        netfree_profile: 1,
        last_name: "הרשברג",
        submit_form_4014: true,
      },
      {
        last_form_date: "2023-12-06T11:01:01.920000Z",
        marksheet: "",
        age: "",
        hok_donor: false,
        first_name_4: "",
        "style_-_source": "",
        car: "",
        language_at_home: "",
        "husband's_occupation": "",
        "woman's_occupation": "",
        "first_name_-_owner": "משה",
        "first_name_-_woman": "שרה",
        "b.r.": "",
        home_phone_1: "+97232561236",
        woman_phone: "+972536547896",
        email: "rctrlaltdel@gmail.com",
        home_phone: "+972586453215",
        city: "בני ברק",
        street: "יזון איש",
        house_number: "15",
        personnel_id_plus: "",
        "שווער_-_חתן": "",
        parent_id_number: "",
        mom_id_number: "",
        zip_code: "",
        children_at_home: "",
        married_children: "",
        full_name: "",
        email_1: "",
        first_name: "",
        last_name_1: "",
        id: 3,
        netfree_profile: 2,
        submit_form_4014: false,
        last_name: "שרה",
      },
      {
        last_form_date: "",
        marksheet: "",
        age: "",
        hok_donor: true,
        first_name_4: "",
        "style_-_source": "",
        car: "",
        language_at_home: "",
        "husband's_occupation": "",
        "woman's_occupation": "",
        "first_name_-_owner": "יוחנן",
        "first_name_-_woman": "חנה",
        "b.r.": "",
        home_phone_1: "+972533109179",
        woman_phone: "+972556736906",
        email: "b1225425@gmail.com",
        home_phone: "",
        city: "בני ברק",
        street: "אמרי ברוך",
        house_number: "",
        personnel_id_plus: "",
        "שווער_-_חתן": "",
        parent_id_number: "",
        mom_id_number: "",
        zip_code: "",
        children_at_home: "",
        married_children: "",
        full_name: "",
        email_1: "",
        first_name: "",
        last_name_1: "",
        id: 4,
        netfree_profile: 3,
        last_name: "טווערסקי",
        submit_form_4014: false,
      },
    ],
    page: 1,
    num_pages: 1,
    next: null,
    previous: null,
    count: 3,
  },
};

export const FULL_FORM_DATA = {
  data: {
    result: [
      {
        is_delete: true,
        is_editable: true,
        display_order: 4,
        block_id: 12,
        block: "Additional",
        field_name_language: {
          en: "Additional",
          he: "פרטים נוספים",
        },
        field: [
          {
            id: 44,
            field_name: "Style - source",
            field_name_language: {
              en: "Style - source",
              he: "סגנון - מקור",
            },
            field_slug: "style_-_source",
            data_type: {
              label: "select",
              value: "select",
            },
            enum_values: {
              choices: [
                {
                  id: 11,
                  value: "סגור במיוחד",
                  label: "סגור במיוחד",
                },
                {
                  id: 12,
                  value: "מודרני",
                  label: "מודרני",
                },
                {
                  id: 13,
                  value: "רעבישע",
                  label: "רעבישע",
                },
                {
                  id: 14,
                  value: "אמריקאי",
                  label: "אמריקאי",
                },
                {
                  id: 15,
                  value: "ירושלמי",
                  label: "ירושלמי",
                },
                {
                  id: 16,
                  value: "קלאסי",
                  label: "קלאסי",
                },
              ],
            },
            required: false,
            defaultvalue: "קלאסי",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 1,
            display: true,
            organization: 1,
          },
          {
            id: 42,
            field_name: "Car",
            field_name_language: {
              en: "Car",
              he: "רכב",
            },
            field_slug: "car",
            data_type: {
              label: "checkbox",
              value: "checkbox",
            },
            enum_values: {},
            required: false,
            defaultvalue: "false",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 2,
            display: true,
            organization: 1,
          },
          {
            id: 43,
            field_name: "Language at home",
            field_name_language: {
              en: "Language at home",
              he: "שפה בבית",
            },
            field_slug: "language_at_home",
            data_type: {
              label: "select",
              value: "select",
            },
            enum_values: {
              choices: [
                {
                  id: 8,
                  value: "אנגלית",
                  label: "אנגלית",
                },
                {
                  id: 9,
                  value: "עברית",
                  label: "עברית",
                },
                {
                  id: 10,
                  value: "אידיש",
                  label: "אידיש",
                },
              ],
            },
            required: false,
            defaultvalue: "עברית",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 3,
            display: true,
            organization: 1,
          },
          {
            id: 45,
            field_name: "Husband's occupation",
            field_name_language: {
              en: "Husband's occupation",
              he: "עיסוק בעל",
            },
            field_slug: "husband's_occupation",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 4,
            display: true,
            organization: 1,
          },
          {
            id: 46,
            field_name: "Woman's occupation",
            field_name_language: {
              en: "Woman's occupation",
              he: "עיסוק אשה",
            },
            field_slug: "woman's_occupation",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 5,
            display: true,
            organization: 1,
          },
        ],
      },
      {
        is_delete: false,
        is_editable: true,
        display_order: 5,
        block_id: 1,
        block: "Personal Informaion",
        field_name_language: {
          en: "Personal informaion",
          he: "פרטים אישיים",
        },
        field: [
          {
            id: 34,
            field_name: "Personnel id plus",
            field_name_language: {
              en: "Personnel id plus",
              he: "מזהה אנש פלוס",
            },
            field_slug: "personnel_id_plus",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: true,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 1,
            display: true,
            organization: 1,
          },
          {
            id: 2,
            field_name: "Last name",
            field_name_language: {
              en: "Last name",
              he: "משפחה",
            },
            field_slug: "last_name",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 2,
            display: false,
            organization: 1,
          },
          {
            id: 1,
            field_name: "First name - owner",
            field_name_language: {
              en: "First name - owner",
              he: "שם פרטי - בעלים",
            },
            field_slug: "first_name_-_owner",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: true,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 3,
            display: true,
            organization: 1,
          },
          {
            id: 30,
            field_name: "First name - woman",
            field_name_language: {
              en: "First name - woman",
              he: "שם פרטי - אישה",
            },
            field_slug: "first_name_-_woman",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: true,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 4,
            display: true,
            organization: 1,
          },
          {
            id: 4,
            field_name: "Home phone",
            field_name_language: {
              en: "Home phone",
              he: "טלפון בעל",
            },
            field_slug: "home_phone_1",
            data_type: {
              label: "phone",
              value: "phone",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 5,
            display: true,
            organization: 1,
          },
          {
            id: 21,
            field_name: "Woman phone",
            field_name_language: {
              en: "Woman phone",
              he: "טלפון אישה",
            },
            field_slug: "woman_phone",
            data_type: {
              label: "phone",
              value: "phone",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 6,
            display: true,
            organization: 1,
          },
          {
            id: 22,
            field_name: "Home phone",
            field_name_language: {
              en: "Home phone",
              he: "טלפון בעל",
            },
            field_slug: "home_phone",
            data_type: {
              label: "phone",
              value: "phone",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 7,
            display: true,
            organization: 1,
          },
          {
            id: 3,
            field_name: "Email",
            field_name_language: {
              en: "Email",
              he: "Email",
            },
            field_slug: "email",
            data_type: {
              label: "email",
              value: "email",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 8,
            display: true,
            organization: 1,
          },
          {
            id: 23,
            field_name: "City",
            field_name_language: {
              en: "City",
              he: "עיר",
            },
            field_slug: "city",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 9,
            display: true,
            organization: 1,
          },
          {
            id: 29,
            field_name: "Street",
            field_name_language: {
              en: "Street",
              he: "רחוב",
            },
            field_slug: "street",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 10,
            display: true,
            organization: 1,
          },
          {
            id: 25,
            field_name: "House number",
            field_name_language: {
              en: "House number",
              he: "מספר בית",
            },
            field_slug: "house_number",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 11,
            display: true,
            organization: 1,
          },
          {
            id: 36,
            field_name: "שווער - חתן",
            field_name_language: {
              en: "שווער - חתן",
              he: "שווער - חתן",
            },
            field_slug: "שווער_-_חתן",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 12,
            display: true,
            organization: 1,
          },
          {
            id: 37,
            field_name: "Parent id number",
            field_name_language: {
              en: "Parent ID number",
              he: "מספר זהות אב",
            },
            field_slug: "parent_id_number",
            data_type: {
              label: "number",
              value: "number",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 13,
            display: true,
            organization: 1,
          },
          {
            id: 38,
            field_name: "Mom id number",
            field_name_language: {
              en: "Mom ID number",
              he: "מספר זהות אמא",
            },
            field_slug: "mom_id_number",
            data_type: {
              label: "number",
              value: "number",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 14,
            display: true,
            organization: 1,
          },
          {
            id: 39,
            field_name: "Zip code",
            field_name_language: {
              en: "Zip code",
              he: "מיקוד",
            },
            field_slug: "zip_code",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 15,
            display: true,
            organization: 1,
          },
          {
            id: 40,
            field_name: "Children at home",
            field_name_language: {
              en: "Children at home",
              he: "ילדים בבית",
            },
            field_slug: "children_at_home",
            data_type: {
              label: "number",
              value: "number",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 16,
            display: true,
            organization: 1,
          },
          {
            id: 56,
            field_name: "Full name",
            field_name_language: {
              en: "Full name",
              he: "Full name",
            },
            field_slug: "full_name",
            data_type: {
              label: "text",
              value: "text",
            },
            enum_values: {},
            required: true,
            defaultvalue: "",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 17,
            display: true,
            organization: 1,
          },
        ],
      },
      {
        is_delete: true,
        is_editable: true,
        display_order: 11,
        block_id: 22,
        block: "מידע משפחתי",
        field_name_language: {
          en: "מידע משפחתי",
          he: "מידע משפחתי",
        },
        field: [],
      },
    ],
  },
};

export const PROFILE_LIST = {
  success: true,
  data: [
    {
      id: 1,
      name: "ברירת מחדל",
      description: "פרופיל ברירת מחדל",
      is_default: true,
      created_at: "2023-10-13T15:37:09.180461Z",
      updated_at: "2023-10-16T17:06:32.683217Z",
      organization: 1,
    },
    {
      id: 12,
      name: "נסיונות",
      description: "בדיקות ונסיונות",
      is_default: false,
      created_at: "2024-01-11T21:38:59.936139Z",
      updated_at: "2024-01-11T21:39:22.852744Z",
      organization: 1,
    },
    {
      id: 41,
      name: "נסיונות_clone",
      description: "בדיקות ונסיונות",
      is_default: false,
      created_at: "2024-05-05T11:19:36.856291Z",
      updated_at: "2024-05-05T11:19:36.856324Z",
      organization: 1,
    },
    {
      id: 45,
      name: "ברירת מחדל_clone",
      description: "פרופיל ברירת מחדל",
      is_default: false,
      created_at: "2024-07-03T09:25:38.932234Z",
      updated_at: "2024-07-03T09:25:38.932266Z",
      organization: 1,
    },
  ],
};

export const SINGLE_CLIENT_DATA = {
  data: {
    client_id: 2,
    blocks: [
      {
        block_id: 12,
        block: "Additional",
        field_name_language: {
          en: "Additional",
          he: "פרטים נוספים",
        },
        field: [
          {
            id: 44,
            field_name: "Style - source",
            field_slug: "style_-_source",
            data_type: {
              label: "select",
              value: "select",
            },
            field_name_language: {
              en: "Style - source",
              he: "סגנון - מקור",
            },
            enum_values: {
              choices: [
                {
                  id: 11,
                  value: "סגור במיוחד",
                  label: "סגור במיוחד",
                },
                {
                  id: 12,
                  value: "מודרני",
                  label: "מודרני",
                },
                {
                  id: 13,
                  value: "רעבישע",
                  label: "רעבישע",
                },
                {
                  id: 14,
                  value: "אמריקאי",
                  label: "אמריקאי",
                },
                {
                  id: 15,
                  value: "ירושלמי",
                  label: "ירושלמי",
                },
                {
                  id: 16,
                  value: "קלאסי",
                  label: "קלאסי",
                },
              ],
            },
            required: false,
            defaultvalue: "קלאסי",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 1,
            display: true,
            value: "",
          },
          {
            id: 42,
            field_name: "Car",
            field_slug: "car",
            data_type: {
              label: "checkbox",
              value: "checkbox",
            },
            field_name_language: {
              en: "Car",
              he: "רכב",
            },
            enum_values: {},
            required: false,
            defaultvalue: "false",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 2,
            display: true,
            value: true,
          },
          {
            id: 43,
            field_name: "Language at home",
            field_slug: "language_at_home",
            data_type: {
              label: "select",
              value: "select",
            },
            field_name_language: {
              en: "Language at home",
              he: "שפה בבית",
            },
            enum_values: {
              choices: [
                {
                  id: 8,
                  value: "אנגלית",
                  label: "אנגלית",
                },
                {
                  id: 9,
                  value: "עברית",
                  label: "עברית",
                },
                {
                  id: 10,
                  value: "אידיש",
                  label: "אידיש",
                },
              ],
            },
            required: false,
            defaultvalue: "עברית",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 3,
            display: true,
            value: "",
          },
          {
            id: 45,
            field_name: "Husband's occupation",
            field_slug: "husband's_occupation",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Husband's occupation",
              he: "עיסוק בעל",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 4,
            display: true,
            value: "",
          },
          {
            id: 46,
            field_name: "Woman's occupation",
            field_slug: "woman's_occupation",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Woman's occupation",
              he: "עיסוק אשה",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 5,
            display: true,
            value: "",
          },
        ],
      },
      {
        block_id: 1,
        block: "Personal Informaion",
        field_name_language: {
          en: "Personal informaion",
          he: "פרטים אישיים",
        },
        field: [
          {
            id: 34,
            field_name: "Personnel id plus",
            field_slug: "personnel_id_plus",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Personnel id plus",
              he: "מזהה אנש פלוס",
            },
            enum_values: {},
            required: true,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 1,
            display: true,
            value: "",
          },
          {
            id: 2,
            field_name: "Last name",
            field_slug: "last_name",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Last name",
              he: "משפחה",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 2,
            display: false,
            value: "הרשברג",
          },
          {
            id: 1,
            field_name: "First name - owner",
            field_slug: "first_name_-_owner",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "First name - owner",
              he: "שם פרטי - בעלים",
            },
            enum_values: {},
            required: true,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 3,
            display: true,
            value: "יצחק יעקב",
          },
          {
            id: 30,
            field_name: "First name - woman",
            field_slug: "first_name_-_woman",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "First name - woman",
              he: "שם פרטי - אישה",
            },
            enum_values: {},
            required: true,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 4,
            display: true,
            value: "",
          },
          {
            id: 4,
            field_name: "Home phone",
            field_slug: "home_phone_1",
            data_type: {
              label: "phone",
              value: "phone",
            },
            field_name_language: {
              en: "Home phone",
              he: "טלפון בעל",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 5,
            display: true,
            value: "+972583230207",
          },
          {
            id: 21,
            field_name: "Woman phone",
            field_slug: "woman_phone",
            data_type: {
              label: "phone",
              value: "phone",
            },
            field_name_language: {
              en: "Woman phone",
              he: "טלפון אישה",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 6,
            display: true,
            value: "+972583230205",
          },
          {
            id: 22,
            field_name: "Home phone",
            field_slug: "home_phone",
            data_type: {
              label: "phone",
              value: "phone",
            },
            field_name_language: {
              en: "Home phone",
              he: "טלפון בעל",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 7,
            display: true,
            value: "+97225630349",
          },
          {
            id: 3,
            field_name: "Email",
            field_slug: "email",
            data_type: {
              label: "email",
              value: "email",
            },
            field_name_language: {
              en: "Email",
              he: "Email",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: false,
            is_editable: true,
            display_order: 8,
            display: true,
            value: "012yyh@gmail.com",
          },
          {
            id: 23,
            field_name: "City",
            field_slug: "city",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "City",
              he: "עיר",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 9,
            display: true,
            value: "ירושלים",
          },
          {
            id: 29,
            field_name: "Street",
            field_slug: "street",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Street",
              he: "רחוב",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 10,
            display: true,
            value: "אלקנה",
          },
          {
            id: 25,
            field_name: "House number",
            field_slug: "house_number",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "House number",
              he: "מספר בית",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 11,
            display: true,
            value: "14",
          },
          {
            id: 36,
            field_name: "שווער - חתן",
            field_slug: "שווער_-_חתן",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "שווער - חתן",
              he: "שווער - חתן",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 12,
            display: true,
            value: "",
          },
          {
            id: 37,
            field_name: "Parent id number",
            field_slug: "parent_id_number",
            data_type: {
              label: "number",
              value: "number",
            },
            field_name_language: {
              en: "Parent ID number",
              he: "מספר זהות אב",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 13,
            display: true,
            value: "",
          },
          {
            id: 38,
            field_name: "Mom id number",
            field_slug: "mom_id_number",
            data_type: {
              label: "number",
              value: "number",
            },
            field_name_language: {
              en: "Mom ID number",
              he: "מספר זהות אמא",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 14,
            display: true,
            value: "",
          },
          {
            id: 39,
            field_name: "Zip code",
            field_slug: "zip_code",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Zip code",
              he: "מיקוד",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 15,
            display: true,
            value: "",
          },
          {
            id: 40,
            field_name: "Children at home",
            field_slug: "children_at_home",
            data_type: {
              label: "number",
              value: "number",
            },
            field_name_language: {
              en: "Children at home",
              he: "ילדים בבית",
            },
            enum_values: {},
            required: false,
            defaultvalue: null,
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 16,
            display: true,
            value: "",
          },
          {
            id: 56,
            field_name: "Full name",
            field_slug: "full_name",
            data_type: {
              label: "text",
              value: "text",
            },
            field_name_language: {
              en: "Full name",
              he: "Full name",
            },
            enum_values: {},
            required: true,
            defaultvalue: "",
            unique: false,
            is_delete: true,
            is_editable: true,
            display_order: 17,
            display: true,
            value: "",
          },
        ],
      },
    ],
    netfree_profile: 1,
  },
};
